import type { User, Student, Subject, Grade, School, TransferRequest } from "./types"

export const mockSchools: School[] = [
  {
    id: "1",
    name: "Escola Municipal João Silva",
    code: "EMJS001",
    address: "Rua das Flores, 123",
    phone: "(11) 1234-5678",
    email: "contato@emjs.edu.br",
  },
  {
    id: "2",
    name: "Colégio Estadual Maria Santos",
    code: "CEMS002",
    address: "Av. Principal, 456",
    phone: "(11) 8765-4321",
    email: "secretaria@cems.edu.br",
  },
  {
    id: "3",
    name: "Instituto Educacional São Paulo",
    code: "IESP003",
    address: "Rua da Educação, 789",
    phone: "(11) 5555-0123",
    email: "contato@iesp.edu.br",
  },
]

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Prof. Ana Costa",
    email: "ana.costa@emjs.edu.br",
    role: "teacher",
    schoolId: "1",
    photo: "/professional-female-teacher-with-glasses-and-frien.jpg",
  },
  {
    id: "2",
    name: "Carlos Oliveira",
    email: "carlos.oliveira@gmail.com",
    role: "parent",
    schoolId: "1",
    photo: "/middle-aged-father-with-beard-and-casual-clothing.jpg",
  },
  {
    id: "3",
    name: "Admin Sistema",
    email: "admin@sistema.edu.br",
    role: "admin",
    schoolId: "1",
    photo: "/professional-administrator-with-suit-and-confident.jpg",
  },
  {
    id: "8",
    name: "Prof. Ricardo Mendes",
    email: "ricardo.mendes@emjs.edu.br",
    role: "admin",
    schoolId: "1",
    photo: "/placeholder-f2qyf.png",
  },
  {
    id: "9",
    name: "Prof. Mariana Silva",
    email: "mariana.silva@cems.edu.br",
    role: "admin",
    schoolId: "2",
    photo: "/placeholder-o32fs.png",
  },
  {
    id: "10",
    name: "Prof. Eduardo Santos",
    email: "eduardo.santos@iesp.edu.br",
    role: "teacher",
    schoolId: "3",
    photo: "/placeholder-7pk6q.png",
  },
  {
    id: "11",
    name: "Prof. Fernanda Lima",
    email: "fernanda.lima@emjs.edu.br",
    role: "teacher",
    schoolId: "1",
    photo: "/placeholder-nyc2x.png",
  },
  {
    id: "12",
    name: "Prof. João Pereira",
    email: "joao.pereira@cems.edu.br",
    role: "admin",
    schoolId: "2",
    photo: "/placeholder-pvh2s.png",
  },
  {
    id: "4",
    name: "Roberto Silva",
    email: "roberto.silva@gmail.com",
    role: "parent",
    schoolId: "1",
  },
  {
    id: "5",
    name: "Carmen Antonieta",
    email: "carmen.antonieta@gmail.com",
    role: "parent",
    schoolId: "1",
  },
  {
    id: "6",
    name: "Fernando del'rei",
    email: "fernando.delrei@gmail.com",
    role: "parent",
    schoolId: "1",
  },
  {
    id: "7",
    name: "Lucia Antonio",
    email: "lucia.antonio@gmail.com",
    role: "parent",
    schoolId: "1",
  },
  {
    id: "13",
    name: "Patricia Alves",
    email: "patricia.alves@gmail.com",
    role: "parent",
    schoolId: "2",
  },
  {
    id: "14",
    name: "Marcos Rodrigues",
    email: "marcos.rodrigues@gmail.com",
    role: "parent",
    schoolId: "2",
  },
  {
    id: "15",
    name: "Juliana Ferreira",
    email: "juliana.ferreira@gmail.com",
    role: "parent",
    schoolId: "3",
  },
  {
    id: "16",
    name: "André Barbosa",
    email: "andre.barbosa@gmail.com",
    role: "parent",
    schoolId: "3",
  },
]

export const mockStudents: Student[] = [
  {
    id: "1",
    name: "João Silva",
    email: "joao.silva@emjs.edu.br",
    parentId: "4",
    schoolId: "1",
    grade: "8º Ano",
    class: "A",
    enrollmentDate: "2024-02-01",
    photo: "/teenage-boy-student-with-school-uniform-and-friend.jpg",
  },
  {
    id: "2",
    name: "Maria Antonieta",
    email: "maria.antonieta@emjs.edu.br",
    parentId: "5",
    schoolId: "1",
    grade: "8º Ano",
    class: "A",
    enrollmentDate: "2024-02-01",
    photo: "/teenage-girl-student-with-long-hair-and-school-uni.jpg",
    specialNeeds: [
      {
        id: "sn1",
        type: "autism",
        description: "Transtorno do Espectro Autista - Síndrome de Asperger",
        accommodations: [
          "Ambiente com menos estímulos visuais",
          "Tempo adicional para provas",
          "Instruções claras e objetivas",
          "Rotina estruturada",
        ],
        severity: "mild",
        supportRequired: [
          "Acompanhamento psicopedagógico",
          "Comunicação frequente com os pais",
          "Adaptações curriculares quando necessário",
        ],
      },
    ],
    medicalInfo: "Acompanhamento com neurologista e psicólogo. Medicação: Risperidona 0,5mg",
    emergencyContact: {
      name: "Ana Silva (avó)",
      phone: "(11) 98765-4321",
      relationship: "Avó",
    },
  },
  {
    id: "3",
    name: "Carlos del'rei",
    email: "carlos.delrei@emjs.edu.br",
    parentId: "6",
    schoolId: "1",
    grade: "8º Ano",
    class: "B",
    enrollmentDate: "2024-02-01",
    photo: "/teenage-boy-student-with-curly-hair-and-school-uni.jpg",
    specialNeeds: [
      {
        id: "sn2",
        type: "wheelchair",
        description: "Cadeirante - Paralisia cerebral",
        accommodations: [
          "Acesso a rampas e elevadores",
          "Mesa adaptada para cadeira de rodas",
          "Banheiro acessível",
          "Localização em sala térrea",
        ],
        severity: "moderate",
        supportRequired: ["Fisioterapia escolar", "Auxiliar para atividades físicas", "Transporte escolar adaptado"],
      },
    ],
    medicalInfo: "Paralisia cerebral espástica. Fisioterapia 3x por semana. Medicação: Baclofeno 10mg",
    emergencyContact: {
      name: "Dr. Roberto Oliveira",
      phone: "(11) 3456-7890",
      relationship: "Médico neurologista",
    },
  },
  {
    id: "4",
    name: "José Antonio",
    email: "jose.antonio@emjs.edu.br",
    parentId: "7",
    schoolId: "1",
    grade: "8º Ano",
    class: "B",
    enrollmentDate: "2024-02-01",
    photo: "/teenage-boy-student-with-glasses-and-school-unifor.jpg",
    specialNeeds: [
      {
        id: "sn3",
        type: "visual_impairment",
        description: "Deficiência visual - Baixa visão",
        accommodations: [
          "Material em fonte ampliada",
          "Lupa eletrônica",
          "Assento próximo ao quadro",
          "Iluminação adequada",
        ],
        severity: "moderate",
        supportRequired: ["Material didático adaptado", "Orientação e mobilidade", "Tecnologia assistiva"],
      },
    ],
    medicalInfo: "Retinose pigmentar. Consultas oftalmológicas trimestrais",
    emergencyContact: {
      name: "Dra. Mariana Luz",
      phone: "(11) 2345-6789",
      relationship: "Oftalmologista",
    },
  },
  {
    id: "5",
    name: "Ana Beatriz Santos",
    email: "ana.santos@emjs.edu.br",
    parentId: "2",
    schoolId: "1",
    grade: "9º Ano",
    class: "A",
    enrollmentDate: "2024-02-01",
    specialNeeds: [
      {
        id: "sn4",
        type: "adhd",
        description: "Transtorno do Déficit de Atenção com Hiperatividade",
        accommodations: [
          "Pausas frequentes durante atividades",
          "Ambiente com menos distrações",
          "Atividades mais dinâmicas",
          "Tempo adicional para tarefas",
        ],
        severity: "moderate",
        supportRequired: ["Acompanhamento psicopedagógico", "Estratégias de organização", "Comunicação com família"],
      },
    ],
    medicalInfo: "TDAH diagnosticado aos 8 anos. Medicação: Metilfenidato 20mg",
    emergencyContact: {
      name: "Psicóloga Fernanda Costa",
      phone: "(11) 9876-5432",
      relationship: "Psicóloga",
    },
  },
  {
    id: "6",
    name: "Pedro Henrique Costa",
    email: "pedro.costa@emjs.edu.br",
    parentId: "8",
    schoolId: "1",
    grade: "9º Ano",
    class: "A",
    enrollmentDate: "2024-02-01",
    specialNeeds: [
      {
        id: "sn5",
        type: "hearing_impairment",
        description: "Deficiência auditiva - Surdez bilateral moderada",
        accommodations: [
          "Intérprete de LIBRAS",
          "Posicionamento frontal ao professor",
          "Material visual complementar",
          "Sistema de FM",
        ],
        severity: "moderate",
        supportRequired: ["Intérprete de LIBRAS", "Fonoaudiologia", "Material didático visual"],
      },
    ],
    medicalInfo: "Surdez congênita bilateral. Uso de aparelho auditivo bilateral",
    emergencyContact: {
      name: "Intérprete Maria LIBRAS",
      phone: "(11) 8765-4321",
      relationship: "Intérprete",
    },
  },
  {
    id: "7",
    name: "Larissa Fernandes",
    email: "larissa.fernandes@emjs.edu.br",
    parentId: "9",
    schoolId: "1",
    grade: "7º Ano",
    class: "A",
    enrollmentDate: "2024-02-01",
    specialNeeds: [
      {
        id: "sn6",
        type: "learning_disability",
        description: "Dislexia e Discalculia",
        accommodations: [
          "Provas orais quando necessário",
          "Tempo adicional para avaliações",
          "Material com fonte diferenciada",
          "Calculadora para matemática",
        ],
        severity: "moderate",
        supportRequired: [
          "Reforço escolar especializado",
          "Acompanhamento psicopedagógico",
          "Métodos alternativos de ensino",
        ],
      },
    ],
    medicalInfo: "Dislexia e discalculia diagnosticadas aos 9 anos. Acompanhamento neuropsicológico",
    emergencyContact: {
      name: "Neuropsicóloga Dra. Paula",
      phone: "(11) 7654-3210",
      relationship: "Neuropsicóloga",
    },
  },
  {
    id: "8",
    name: "Rafael Mendes",
    email: "rafael.mendes@cems.edu.br",
    parentId: "10",
    schoolId: "2",
    grade: "8º Ano",
    class: "A",
    enrollmentDate: "2024-01-15",
    photo: "/placeholder-hn59s.png",
  },
  {
    id: "9",
    name: "Gabriela Rocha",
    email: "gabriela.rocha@iesp.edu.br",
    parentId: "11",
    schoolId: "3",
    grade: "9º Ano",
    class: "B",
    enrollmentDate: "2024-01-20",
    photo: "/placeholder-tv54x.png",
  },
  {
    id: "10",
    name: "Lucas Almeida",
    email: "lucas.almeida@cems.edu.br",
    parentId: "13",
    schoolId: "2",
    grade: "7º Ano",
    class: "A",
    enrollmentDate: "2024-01-15",
    photo: "/placeholder-uuvex.png",
  },
  {
    id: "11",
    name: "Isabella Martins",
    email: "isabella.martins@cems.edu.br",
    parentId: "13",
    schoolId: "2",
    grade: "8º Ano",
    class: "B",
    enrollmentDate: "2024-01-15",
    photo: "/placeholder-gv7kh.png",
  },
  {
    id: "12",
    name: "Thiago Rodrigues",
    email: "thiago.rodrigues@cems.edu.br",
    parentId: "14",
    schoolId: "2",
    grade: "9º Ano",
    class: "A",
    enrollmentDate: "2024-01-15",
    photo: "/placeholder-fqn7w.png",
  },
  {
    id: "13",
    name: "Camila Ferreira",
    email: "camila.ferreira@iesp.edu.br",
    parentId: "15",
    schoolId: "3",
    grade: "7º Ano",
    class: "C",
    enrollmentDate: "2024-01-20",
    photo: "/placeholder-w96zy.png",
  },
  {
    id: "14",
    name: "Bruno Barbosa",
    email: "bruno.barbosa@iesp.edu.br",
    parentId: "16",
    schoolId: "3",
    grade: "8º Ano",
    class: "A",
    enrollmentDate: "2024-01-20",
    photo: "/placeholder-hn59s.png",
  },
  {
    id: "15",
    name: "Sophia Lima",
    email: "sophia.lima@iesp.edu.br",
    parentId: "15",
    schoolId: "3",
    grade: "9º Ano",
    class: "B",
    enrollmentDate: "2024-01-20",
    photo: "/placeholder-tv54x.png",
  },
]

export const mockSubjects: Subject[] = [
  {
    id: "1",
    name: "Matemática",
    teacherId: "1",
    schoolId: "1",
    grade: "8º Ano",
  },
  {
    id: "2",
    name: "Português",
    teacherId: "1",
    schoolId: "1",
    grade: "8º Ano",
  },
  {
    id: "3",
    name: "História",
    teacherId: "1",
    schoolId: "1",
    grade: "8º Ano",
  },
  {
    id: "4",
    name: "Geografia",
    teacherId: "1",
    schoolId: "1",
    grade: "8º Ano",
  },
  {
    id: "5",
    name: "Educação Física",
    teacherId: "1",
    schoolId: "1",
    grade: "8º Ano",
  },
  {
    id: "6",
    name: "Artes",
    teacherId: "1",
    schoolId: "1",
    grade: "8º Ano",
  },
  {
    id: "7",
    name: "Informática",
    teacherId: "1",
    schoolId: "1",
    grade: "8º Ano",
  },
  // Matérias para 9º Ano
  {
    id: "8",
    name: "Matemática",
    teacherId: "1",
    schoolId: "1",
    grade: "9º Ano",
  },
  {
    id: "9",
    name: "Português",
    teacherId: "1",
    schoolId: "1",
    grade: "9º Ano",
  },
  {
    id: "10",
    name: "História",
    teacherId: "1",
    schoolId: "1",
    grade: "9º Ano",
  },
  {
    id: "11",
    name: "Geografia",
    teacherId: "1",
    schoolId: "1",
    grade: "9º Ano",
  },
  {
    id: "12",
    name: "Educação Física",
    teacherId: "1",
    schoolId: "1",
    grade: "9º Ano",
  },
  {
    id: "13",
    name: "Artes",
    teacherId: "1",
    schoolId: "1",
    grade: "9º Ano",
  },
  {
    id: "14",
    name: "Informática",
    teacherId: "1",
    schoolId: "1",
    grade: "9º Ano",
  },
  // Matérias para 7º Ano
  {
    id: "15",
    name: "Matemática",
    teacherId: "1",
    schoolId: "1",
    grade: "7º Ano",
  },
  {
    id: "16",
    name: "Português",
    teacherId: "1",
    schoolId: "1",
    grade: "7º Ano",
  },
  {
    id: "17",
    name: "História",
    teacherId: "1",
    schoolId: "1",
    grade: "7º Ano",
  },
  {
    id: "18",
    name: "Geografia",
    teacherId: "1",
    schoolId: "1",
    grade: "7º Ano",
  },
  {
    id: "19",
    name: "Educação Física",
    teacherId: "1",
    schoolId: "1",
    grade: "7º Ano",
  },
  {
    id: "20",
    name: "Artes",
    teacherId: "1",
    schoolId: "1",
    grade: "7º Ano",
  },
  {
    id: "21",
    name: "Informática",
    teacherId: "1",
    schoolId: "1",
    grade: "7º Ano",
  },
]

export const mockGrades: Grade[] = [
  // João Silva (id: 1) - 8º Ano - Múltiplas avaliações por matéria
  // Matemática - Evolução ao longo do ano
  {
    id: "1",
    studentId: "1",
    subjectId: "1",
    value: 7.0,
    maxValue: 10,
    type: "exam",
    date: "2024-02-15",
    description: "1ª Avaliação - Números Racionais",
  },
  {
    id: "1a",
    studentId: "1",
    subjectId: "1",
    value: 8.5,
    maxValue: 10,
    type: "exam",
    date: "2024-03-15",
    description: "2ª Avaliação - Álgebra",
  },
  {
    id: "1b",
    studentId: "1",
    subjectId: "1",
    value: 9.2,
    maxValue: 10,
    type: "exam",
    date: "2024-04-15",
    description: "3ª Avaliação - Geometria",
  },

  // Português - Evolução
  {
    id: "2",
    studentId: "1",
    subjectId: "2",
    value: 8.8,
    maxValue: 10,
    type: "assignment",
    date: "2024-02-20",
    description: "1ª Redação - Narrativa",
  },
  {
    id: "2a",
    studentId: "1",
    subjectId: "2",
    value: 9.2,
    maxValue: 10,
    type: "assignment",
    date: "2024-03-20",
    description: "2ª Redação - Dissertativa",
  },
  {
    id: "2b",
    studentId: "1",
    subjectId: "2",
    value: 9.5,
    maxValue: 10,
    type: "assignment",
    date: "2024-04-20",
    description: "3ª Redação - Argumentativa",
  },

  // História - Evolução com dificuldades iniciais
  {
    id: "3",
    studentId: "1",
    subjectId: "3",
    value: 4.5, // Nota vermelha inicial em História
    maxValue: 10,
    type: "exam",
    date: "2024-02-18",
    description: "1ª Prova - Descobrimentos",
  },
  {
    id: "3a",
    studentId: "1",
    subjectId: "3",
    value: 6.2,
    maxValue: 10,
    type: "exam",
    date: "2024-03-18",
    description: "2ª Prova - Brasil Colônia",
  },
  {
    id: "3b",
    studentId: "1",
    subjectId: "3",
    value: 7.8,
    maxValue: 10,
    type: "exam",
    date: "2024-04-18",
    description: "3ª Prova - Independência",
  },

  // Geografia - Evolução
  {
    id: "4",
    studentId: "1",
    subjectId: "4",
    value: 7.5,
    maxValue: 10,
    type: "assignment",
    date: "2024-02-22",
    description: "1º Trabalho - Cartografia",
  },
  {
    id: "4a",
    studentId: "1",
    subjectId: "4",
    value: 8.0,
    maxValue: 10,
    type: "assignment",
    date: "2024-03-22",
    description: "2º Trabalho - Relevo",
  },
  {
    id: "4b",
    studentId: "1",
    subjectId: "4",
    value: 8.7,
    maxValue: 10,
    type: "assignment",
    date: "2024-04-22",
    description: "3º Trabalho - Clima",
  },

  // Educação Física - Evolução
  {
    id: "5",
    studentId: "1",
    subjectId: "5",
    value: 9.0,
    maxValue: 10,
    type: "participation",
    date: "2024-02-25",
    description: "1ª Avaliação - Futsal",
  },
  {
    id: "5a",
    studentId: "1",
    subjectId: "5",
    value: 9.5,
    maxValue: 10,
    type: "participation",
    date: "2024-03-25",
    description: "2ª Avaliação - Voleibol",
  },
  {
    id: "5b",
    studentId: "1",
    subjectId: "5",
    value: 9.8,
    maxValue: 10,
    type: "participation",
    date: "2024-04-25",
    description: "3ª Avaliação - Basquete",
  },

  // Artes - Evolução com dificuldades
  {
    id: "6",
    studentId: "1",
    subjectId: "6",
    value: 5.2, // Nota vermelha em Artes
    maxValue: 10,
    type: "assignment",
    date: "2024-02-28",
    description: "1º Projeto - Desenho",
  },
  {
    id: "6a",
    studentId: "1",
    subjectId: "6",
    value: 6.7,
    maxValue: 10,
    type: "assignment",
    date: "2024-03-28",
    description: "2º Projeto - Pintura",
  },
  {
    id: "6b",
    studentId: "1",
    subjectId: "6",
    value: 8.1,
    maxValue: 10,
    type: "assignment",
    date: "2024-04-28",
    description: "3º Projeto - Escultura",
  },

  // Informática - Dificuldades iniciais
  {
    id: "7",
    studentId: "1",
    subjectId: "7",
    value: 4.8, // Nota vermelha em Informática
    maxValue: 10,
    type: "assignment",
    date: "2024-03-01",
    description: "1º Projeto - HTML Básico",
  },
  {
    id: "7a",
    studentId: "1",
    subjectId: "7",
    value: 6.5,
    maxValue: 10,
    type: "assignment",
    date: "2024-04-01",
    description: "2º Projeto - CSS",
  },
  {
    id: "7b",
    studentId: "1",
    subjectId: "7",
    value: 7.9,
    maxValue: 10,
    type: "assignment",
    date: "2024-05-01",
    description: "3º Projeto - JavaScript",
  },

  // Maria Antonieta (id: 2) - 8º Ano - Múltiplas avaliações
  // Matemática - Evolução com dificuldades iniciais
  {
    id: "8",
    studentId: "2",
    subjectId: "1",
    value: 4.2, // Nota vermelha inicial em Matemática
    maxValue: 10,
    type: "exam",
    date: "2024-02-15",
    description: "1ª Avaliação - Números Racionais",
  },
  {
    id: "8a",
    studentId: "2",
    subjectId: "1",
    value: 6.5,
    maxValue: 10,
    type: "exam",
    date: "2024-03-15",
    description: "2ª Avaliação - Álgebra",
  },
  {
    id: "8b",
    studentId: "2",
    subjectId: "1",
    value: 7.8,
    maxValue: 10,
    type: "exam",
    date: "2024-04-15",
    description: "3ª Avaliação - Geometria",
  },
  {
    id: "24",
    studentId: "2",
    subjectId: "1",
    value: 2.3, // Nota crítica em Matemática
    maxValue: 10,
    type: "exam",
    date: "2024-02-10",
    description: "1ª Avaliação - Frações",
  },
  {
    id: "24a",
    studentId: "2",
    subjectId: "1",
    value: 1.9, // Piorou drasticamente
    maxValue: 10,
    type: "exam",
    date: "2024-03-10",
    description: "2ª Avaliação - Equações",
  },
  {
    id: "24b",
    studentId: "2",
    subjectId: "1",
    value: 3.6, // Recuperou um pouco com reforço
    maxValue: 10,
    type: "exam",
    date: "2024-04-10",
    description: "3ª Avaliação - Geometria Básica",
  },

  // Português - Forte desempenho
  {
    id: "9",
    studentId: "2",
    subjectId: "2",
    value: 9.5,
    maxValue: 10,
    type: "assignment",
    date: "2024-02-20",
    description: "1ª Redação - Narrativa",
  },
  {
    id: "9a",
    studentId: "2",
    subjectId: "2",
    value: 9.8,
    maxValue: 10,
    type: "assignment",
    date: "2024-03-20",
    description: "2ª Redação - Dissertativa",
  },
  {
    id: "9b",
    studentId: "2",
    subjectId: "2",
    value: 9.2,
    maxValue: 10,
    type: "assignment",
    date: "2024-04-20",
    description: "3ª Redação - Argumentativa",
  },

  // História - Dificuldades
  {
    id: "10",
    studentId: "2",
    subjectId: "3",
    value: 5.8, // Nota vermelha em História
    maxValue: 10,
    type: "exam",
    date: "2024-02-18",
    description: "1ª Prova - Descobrimentos",
  },
  {
    id: "10a",
    studentId: "2",
    subjectId: "3",
    value: 6.4,
    maxValue: 10,
    type: "exam",
    date: "2024-03-18",
    description: "2ª Prova - Brasil Colônia",
  },
  {
    id: "10b",
    studentId: "2",
    subjectId: "3",
    value: 7.1,
    maxValue: 10,
    type: "exam",
    date: "2024-04-18",
    description: "3ª Prova - Independência",
  },

  // Geografia - Desempenho médio
  {
    id: "11",
    studentId: "2",
    subjectId: "4",
    value: 7.2,
    maxValue: 10,
    type: "assignment",
    date: "2024-02-22",
    description: "1º Trabalho - Cartografia",
  },
  {
    id: "11a",
    studentId: "2",
    subjectId: "4",
    value: 7.8,
    maxValue: 10,
    type: "assignment",
    date: "2024-03-22",
    description: "2º Trabalho - Relevo",
  },
  {
    id: "11b",
    studentId: "2",
    subjectId: "4",
    value: 8.3,
    maxValue: 10,
    type: "assignment",
    date: "2024-04-22",
    description: "3º Trabalho - Clima",
  },

  // Educação Física - Dificuldades
  {
    id: "12",
    studentId: "2",
    subjectId: "5",
    value: 5.5, // Nota vermelha em Educação Física
    maxValue: 10,
    type: "participation",
    date: "2024-02-25",
    description: "1ª Avaliação - Futsal",
  },
  {
    id: "12a",
    studentId: "2",
    subjectId: "5",
    value: 6.8,
    maxValue: 10,
    type: "participation",
    date: "2024-03-25",
    description: "2ª Avaliação - Voleibol",
  },
  {
    id: "12b",
    studentId: "2",
    subjectId: "5",
    value: 7.5,
    maxValue: 10,
    type: "participation",
    date: "2024-04-25",
    description: "3ª Avaliação - Basquete",
  },

  // Artes - Excelente desempenho
  {
    id: "13",
    studentId: "2",
    subjectId: "6",
    value: 9.3,
    maxValue: 10,
    type: "assignment",
    date: "2024-02-28",
    description: "1º Projeto - Desenho",
  },
  {
    id: "13a",
    studentId: "2",
    subjectId: "6",
    value: 9.7,
    maxValue: 10,
    type: "assignment",
    date: "2024-03-28",
    description: "2º Projeto - Pintura",
  },
  {
    id: "13b",
    studentId: "2",
    subjectId: "6",
    value: 9.5,
    maxValue: 10,
    type: "assignment",
    date: "2024-04-28",
    description: "3º Projeto - Escultura",
  },

  // Informática - Dificuldades
  {
    id: "14",
    studentId: "2",
    subjectId: "7",
    value: 4.9, // Nota vermelha em Informática
    maxValue: 10,
    type: "assignment",
    date: "2024-03-01",
    description: "1º Projeto - HTML Básico",
  },
  {
    id: "14a",
    studentId: "2",
    subjectId: "7",
    value: 5.8,
    maxValue: 10,
    type: "assignment",
    date: "2024-04-01",
    description: "2º Projeto - CSS",
  },
  {
    id: "14b",
    studentId: "2",
    subjectId: "7",
    value: 6.9,
    maxValue: 10,
    type: "assignment",
    date: "2024-05-01",
    description: "3º Projeto - JavaScript",
  },

  // Carlos del'rei (id: 3) - 8º Ano - Dificuldades em matemática, forte em educação física
  // Matemática - Dificuldades persistentes
  {
    id: "15",
    studentId: "3",
    subjectId: "1",
    value: 2.1, // Nota muito baixa - dificuldades severas
    maxValue: 10,
    type: "exam",
    date: "2024-02-15",
    description: "1ª Avaliação - Números Racionais",
  },
  {
    id: "15a",
    studentId: "3",
    subjectId: "1",
    value: 2.8, // Ainda muito baixa
    maxValue: 10,
    type: "exam",
    date: "2024-03-15",
    description: "2ª Avaliação - Álgebra",
  },
  {
    id: "15b",
    studentId: "3",
    subjectId: "1",
    value: 3.2, // Pequena melhora mas ainda crítica
    maxValue: 10,
    type: "exam",
    date: "2024-04-15",
    description: "3ª Avaliação - Geometria",
  },
  {
    id: "15c",
    studentId: "3",
    subjectId: "1",
    value: 3.8,
    maxValue: 10,
    type: "exam",
    date: "2024-05-15",
    description: "4ª Avaliação - Estatística",
  },

  // Português - Dificuldades de interpretação
  {
    id: "16",
    studentId: "3",
    subjectId: "2",
    value: 3.5, // Nota muito baixa em Português
    maxValue: 10,
    type: "exam",
    date: "2024-02-20",
    description: "1ª Avaliação - Interpretação de Texto",
  },
  {
    id: "16a",
    studentId: "3",
    subjectId: "2",
    value: 2.9, // Piorou - nota crítica
    maxValue: 10,
    type: "exam",
    date: "2024-03-20",
    description: "2ª Avaliação - Gramática",
  },
  {
    id: "16b",
    studentId: "3",
    subjectId: "2",
    value: 3.7, // Leve melhora mas ainda baixa
    maxValue: 10,
    type: "exam",
    date: "2024-04-20",
    description: "3ª Avaliação - Redação",
  },

  // História - Dificuldades com datas e contextos
  {
    id: "17",
    studentId: "3",
    subjectId: "3",
    value: 2.5, // Nota crítica em História
    maxValue: 10,
    type: "exam",
    date: "2024-02-25",
    description: "1ª Avaliação - Brasil Colonial",
  },
  {
    id: "17a",
    studentId: "3",
    subjectId: "3",
    value: 3.1, // Pequena melhora mas ainda crítica
    maxValue: 10,
    type: "exam",
    date: "2024-03-25",
    description: "2ª Avaliação - Independência",
  },

  // Geografia - Dificuldades com mapas e conceitos
  {
    id: "18",
    studentId: "3",
    subjectId: "4",
    value: 3.0, // Nota muito baixa em Geografia
    maxValue: 10,
    type: "exam",
    date: "2024-03-01",
    description: "1ª Avaliação - Relevo Brasileiro",
  },
  {
    id: "18a",
    studentId: "3",
    subjectId: "4",
    value: 2.7, // Piorou - situação crítica
    maxValue: 10,
    type: "exam",
    date: "2024-04-01",
    description: "2ª Avaliação - Clima e Vegetação",
  },

  // Educação Física - Evolução
  {
    id: "19",
    studentId: "3",
    subjectId: "5",
    value: 9.8,
    maxValue: 10,
    type: "participation",
    date: "2024-02-25",
    description: "1ª Avaliação - Futsal",
  },
  {
    id: "19a",
    studentId: "3",
    subjectId: "5",
    value: 9.9,
    maxValue: 10,
    type: "participation",
    date: "2024-03-25",
    description: "2ª Avaliação - Voleibol",
  },
  {
    id: "19b",
    studentId: "3",
    subjectId: "5",
    value: 10.0,
    maxValue: 10,
    type: "participation",
    date: "2024-04-25",
    description: "3ª Avaliação - Basquete",
  },

  // Artes - Desempenho médio
  {
    id: "20",
    studentId: "3",
    subjectId: "6",
    value: 6.8,
    maxValue: 10,
    type: "assignment",
    date: "2024-02-28",
    description: "1º Projeto - Desenho",
  },
  {
    id: "20a",
    studentId: "3",
    subjectId: "6",
    value: 7.2,
    maxValue: 10,
    type: "assignment",
    date: "2024-03-28",
    description: "2º Projeto - Pintura",
  },
  {
    id: "20b",
    studentId: "3",
    subjectId: "6",
    value: 7.8,
    maxValue: 10,
    type: "assignment",
    date: "2024-04-28",
    description: "3º Projeto - Escultura",
  },

  // Informática - Grandes dificuldades
  {
    id: "21",
    studentId: "3",
    subjectId: "7",
    value: 1.8, // Nota extremamente baixa
    maxValue: 10,
    type: "assignment",
    date: "2024-03-01",
    description: "1º Projeto - HTML Básico",
  },
  {
    id: "21a",
    studentId: "3",
    subjectId: "7",
    value: 2.4, // Ainda crítica
    maxValue: 10,
    type: "assignment",
    date: "2024-04-01",
    description: "2º Projeto - CSS",
  },
  {
    id: "21b",
    studentId: "3",
    subjectId: "7",
    value: 3.1, // Melhora mas ainda muito baixa
    maxValue: 10,
    type: "assignment",
    date: "2024-05-01",
    description: "3º Projeto - JavaScript",
  },

  // José Antonio (id: 4) - 8º Ano - Desempenho equilibrado com algumas dificuldades
  // Matemática - Desempenho médio
  {
    id: "22",
    studentId: "4",
    subjectId: "1",
    value: 7.2,
    maxValue: 10,
    type: "exam",
    date: "2024-02-15",
    description: "1ª Avaliação - Números Racionais",
  },
  {
    id: "22a",
    studentId: "4",
    subjectId: "1",
    value: 6.8,
    maxValue: 10,
    type: "exam",
    date: "2024-03-15",
    description: "2ª Avaliação - Álgebra",
  },
  {
    id: "22b",
    studentId: "4",
    subjectId: "1",
    value: 7.5,
    maxValue: 10,
    type: "exam",
    date: "2024-04-15",
    description: "3ª Avaliação - Geometria",
  },

  // Português - Dificuldades iniciais
  {
    id: "23",
    studentId: "4",
    subjectId: "2",
    value: 3.8, // Nota baixa em Português
    maxValue: 10,
    type: "exam",
    date: "2024-02-18",
    description: "1ª Avaliação - Ortografia",
  },
  {
    id: "23a",
    studentId: "4",
    subjectId: "2",
    value: 2.6, // Piorou significativamente
    maxValue: 10,
    type: "exam",
    date: "2024-03-18",
    description: "2ª Avaliação - Sintaxe",
  },
  {
    id: "23b",
    studentId: "4",
    subjectId: "2",
    value: 4.2, // Recuperou um pouco
    maxValue: 10,
    type: "exam",
    date: "2024-04-18",
    description: "3ª Avaliação - Literatura",
  },

  // História - Dificuldades
  {
    id: "24",
    studentId: "4",
    subjectId: "3",
    value: 3.4, // Nota baixa em História
    maxValue: 10,
    type: "exam",
    date: "2024-02-22",
    description: "1ª Avaliação - Idade Média",
  },
  {
    id: "24a",
    studentId: "4",
    subjectId: "3",
    value: 2.9, // Piorou
    maxValue: 10,
    type: "exam",
    date: "2024-03-22",
    description: "2ª Avaliação - Renascimento",
  },

  // Ana Beatriz Santos (id: 5) - 9º Ano
  {
    id: "29",
    studentId: "5",
    subjectId: "8",
    value: 8.9,
    maxValue: 10,
    type: "exam",
    date: "2024-03-16",
    description: "Prova - Funções Quadráticas",
  },
  {
    id: "30",
    studentId: "5",
    subjectId: "9",
    value: 9.1,
    maxValue: 10,
    type: "assignment",
    date: "2024-03-21",
    description: "Análise Literária - Machado de Assis",
  },
  {
    id: "31",
    studentId: "5",
    subjectId: "10",
    value: 8.6,
    maxValue: 10,
    type: "exam",
    date: "2024-03-19",
    description: "Prova - República Velha",
  },
  {
    id: "32",
    studentId: "5",
    subjectId: "11",
    value: 7.9,
    maxValue: 10,
    type: "assignment",
    date: "2024-03-23",
    description: "Trabalho - Urbanização",
  },
  {
    id: "33",
    studentId: "5",
    subjectId: "12",
    value: 9.2,
    maxValue: 10,
    type: "participation",
    date: "2024-03-26",
    description: "Avaliação - Atletismo",
  },
  {
    id: "34",
    studentId: "5",
    subjectId: "13",
    value: 8.4,
    maxValue: 10,
    type: "assignment",
    date: "2024-03-29",
    description: "Projeto - Arte Moderna",
  },
  {
    id: "35",
    studentId: "5",
    subjectId: "14",
    value: 8.8,
    maxValue: 10,
    type: "exam",
    date: "2024-03-31",
    description: "Prova - Banco de Dados",
  },

  // Pedro Henrique Costa (id: 6) - 9º Ano
  {
    id: "36",
    studentId: "6",
    subjectId: "8",
    value: 7.3,
    maxValue: 10,
    type: "exam",
    date: "2024-03-16",
    description: "Prova - Funções Quadráticas",
  },
  {
    id: "37",
    studentId: "6",
    subjectId: "9",
    value: 8.5,
    maxValue: 10,
    type: "assignment",
    date: "2024-03-21",
    description: "Análise Literária - Machado de Assis",
  },
  {
    id: "38",
    studentId: "6",
    subjectId: "10",
    value: 9.0,
    maxValue: 10,
    type: "exam",
    date: "2024-03-19",
    description: "Prova - República Velha",
  },
  {
    id: "39",
    studentId: "6",
    subjectId: "11",
    value: 8.2,
    maxValue: 10,
    type: "assignment",
    date: "2024-03-23",
    description: "Trabalho - Urbanização",
  },
  {
    id: "40",
    studentId: "6",
    subjectId: "12",
    value: 8.7,
    maxValue: 10,
    type: "participation",
    date: "2024-03-26",
    description: "Avaliação - Atletismo",
  },
  {
    id: "41",
    studentId: "6",
    subjectId: "13",
    value: 7.6,
    maxValue: 10,
    type: "assignment",
    date: "2024-03-29",
    description: "Projeto - Arte Moderna",
  },
  {
    id: "42",
    studentId: "6",
    subjectId: "14",
    value: 9.1,
    maxValue: 10,
    type: "exam",
    date: "2024-03-31",
    description: "Prova - Banco de Dados",
  },

  // Larissa Fernandes (id: 7) - 7º Ano
  {
    id: "43",
    studentId: "7",
    subjectId: "15",
    value: 8.2,
    maxValue: 10,
    type: "exam",
    date: "2024-03-14",
    description: "Prova - Números Inteiros",
  },
  {
    id: "44",
    studentId: "7",
    subjectId: "16",
    value: 7.8,
    maxValue: 10,
    type: "assignment",
    date: "2024-03-19",
    description: "Produção Textual - Crônica",
  },
  {
    id: "45",
    studentId: "7",
    subjectId: "17",
    value: 8.9,
    maxValue: 10,
    type: "exam",
    date: "2024-03-17",
    description: "Prova - Idade Média",
  },
  {
    id: "46",
    studentId: "7",
    subjectId: "18",
    value: 8.4,
    maxValue: 10,
    type: "assignment",
    date: "2024-03-21",
    description: "Trabalho - Clima do Brasil",
  },
  {
    id: "47",
    studentId: "7",
    subjectId: "19",
    value: 9.6,
    maxValue: 10,
    type: "participation",
    date: "2024-03-24",
    description: "Avaliação - Handebol",
  },
  {
    id: "48",
    studentId: "7",
    subjectId: "20",
    value: 8.3,
    maxValue: 10,
    type: "assignment",
    date: "2024-03-27",
    description: "Projeto - Desenho Artístico",
  },
  {
    id: "49",
    studentId: "7",
    subjectId: "21",
    value: 7.9,
    maxValue: 10,
    type: "exam",
    date: "2024-03-29",
    description: "Prova - Introdução à Informática",
  },

  // Rafael Mendes (id: 8) - Aluno transferido
  {
    id: "50",
    studentId: "8",
    subjectId: "1",
    value: 6.5,
    maxValue: 10,
    type: "exam",
    date: "2024-01-20",
    description: "Prova - Álgebra (Escola Anterior)",
  },
  {
    id: "51",
    studentId: "8",
    subjectId: "2",
    value: 7.2,
    maxValue: 10,
    type: "assignment",
    date: "2024-01-25",
    description: "Redação (Escola Anterior)",
  },
  {
    id: "52",
    studentId: "8",
    subjectId: "3",
    value: 8.1,
    maxValue: 10,
    type: "exam",
    date: "2024-01-28",
    description: "História (Escola Anterior)",
  },
  {
    id: "53",
    studentId: "8",
    subjectId: "4",
    value: 7.8,
    maxValue: 10,
    type: "assignment",
    date: "2024-01-30",
    description: "Geografia (Escola Anterior)",
  },

  // Gabriela Rocha (id: 9) - Aluna transferida
  {
    id: "54",
    studentId: "9",
    subjectId: "8",
    value: 9.2,
    maxValue: 10,
    type: "exam",
    date: "2024-01-22",
    description: "Matemática (Escola Anterior)",
  },
  {
    id: "55",
    studentId: "9",
    subjectId: "9",
    value: 8.7,
    maxValue: 10,
    type: "assignment",
    date: "2024-01-27",
    description: "Português (Escola Anterior)",
  },
  {
    id: "56",
    studentId: "9",
    subjectId: "10",
    value: 8.9,
    maxValue: 10,
    type: "exam",
    date: "2024-01-29",
    description: "História (Escola Anterior)",
  },
  {
    id: "57",
    studentId: "9",
    subjectId: "11",
    value: 8.4,
    maxValue: 10,
    type: "assignment",
    date: "2024-02-01",
    description: "Geografia (Escola Anterior)",
  },
]

export const mockTransferRequests: TransferRequest[] = [
  {
    id: "1",
    studentId: "8",
    fromSchoolId: "1",
    toSchoolId: "2",
    status: "approved",
    requestDate: "2024-01-10",
    approvalDate: "2024-01-15",
    transferData: {
      grades: mockGrades.filter((g) => ["50", "51", "52", "53"].includes(g.id)),
      attendance: 88,
      disciplinaryRecords: [],
      medicalInfo: "Nenhuma restrição médica",
    },
  },
  {
    id: "2",
    studentId: "9",
    fromSchoolId: "1",
    toSchoolId: "3",
    status: "approved",
    requestDate: "2024-01-15",
    approvalDate: "2024-01-20",
    transferData: {
      grades: mockGrades.filter((g) => ["54", "55", "56", "57"].includes(g.id)),
      attendance: 95,
      disciplinaryRecords: [],
      medicalInfo: "Alergia a frutos do mar",
    },
  },
  {
    id: "3",
    studentId: "3",
    fromSchoolId: "1",
    toSchoolId: "2",
    status: "pending",
    requestDate: "2024-03-25",
    transferData: {
      grades: mockGrades.filter((g) => g.studentId === "3"),
      attendance: 92,
      disciplinaryRecords: ["Advertência - Atraso frequente"],
      medicalInfo: "Usa óculos para miopia",
    },
  },
]
